# This workflow compiles CSPICE for many architectures and publishes a branch
# to Test-PyPi or PyPi

name: Publish to PyPI

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

jobs:
  build_python3_wheels:
    name: Build Python 3 wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        python-version: [ '3.11' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.8'
          CIBW_BEFORE_BUILD: 'pip3 install numpy setuptools && python3 setup.py generate'
          CIBW_SKIP: 'pp* *musllinux* *cp27mu*'
          CIBW_ARCHS: 'auto64'
          CIBW_ARCHS_MACOS: 'x86_64 arm64'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build sdist
        run: |
          printenv
          sudo apt install swig
          pip install numpy setuptools setuptools-scm wheel
          python3 setup.py generate
          python3 setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz


  upload_pypi:
    needs: [build_python3_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact   # prevents extra directory
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify-metadata: false
